### ISSUE TITLE
Saving the file in document management

### ISSUE THREAD

**Issue by flotho** [WilldooIT/Pentaho-reports-for-OpenERP#72] opened 2013-11-26 18:59 UTC
Hy,

I use your tips for replacing the dafult invoice report. It's perfect.
Unfortunatley, it doesn't store the file in mangement system even if I copy exactly the parameters of the default in the pentaho report config.

What am I missing?

regards

**Comment by richard-willdooit** [comment] 2013-11-26 22:20
The latest version should now work correctly with the DMS.  Please ensure you have pulled and run with the latest code-base.

Special note: With the latest version, the tips regarding how to make the standard reports to Pentaho reports are no longer applicable.  In the latest version (only in the version70 branch) the report actions and Pentaho report actions appear together in the report actions menu.  Switching a report between them is now just a checkbox.

**Comment by flotho** [comment] 2013-11-29 19:22
Hy richard,

Thansk.
Did you mean that this enhancement is not in the pentaho_39 branch and only work with pentaho 50 in the 70 branch?

Thanks

**Comment by flotho** [comment] 2013-12-01 17:22
Hy Richard,

Thanks for your patch, storing the file save correctly the file withe the good name.
I think there a last point to consider. If you check the option to reload the file from the one already store, it runs another time the pentaho report and save it twice.
I thins it's not the default behavior of the document management.

Thanks anyway.

regards

**Comment by flotho** [comment] 2013-12-01 17:25
One more question,

If I remember well, the report is supposed to be saved when you validate the invoice. Am I wrong?

regards

**Comment by richard-willdooit** [comment] 2013-12-01 21:46
You are correct - the "reload from saved" option is not working correctly.  This is noted, and if someone rectifies it, we will merge it in.  If I have some time in the near future, I may look at it myself.

**Comment by flotho** [comment] 2013-12-01 22:04
Thanks for your confirmation.

I'll dig in in the future on this part.
Anyway, thanks for the great job.

**Comment by richard-willdooit** [comment] 2014-09-29 23:48
Will leave the other request open, and close this.
Duplicate of #145

**Closed as completed by richard-willdooit** 2014-09-29 23:48 UTC
